import org.junit.Test
import org.junit.Assert.*

class WallServiceTest {

    @Test
    fun add() {
        val serviceEnter0 = WallService()
        serviceEnter0.add(Post(0,
            25,
            59,
            12,
            1647797692,
            "New Netology Post",
            37,
            84,
            true,
            Post.Comments(2, true, 4, canClose = false, canOpen = false),
            Post.Copyright(83, "https://--", "Some Name", "Some Type"),
            Post.Likes(95, userLikes = false, canLike = true, canPublish = false),
            Post.Reposts(47, true),
            Post.Views(2),
            Post.PostType.post,
            25,
            canPin = true,
            canDelete = false,
            canEdit = false,
            isPinned = true,
            markedAsAds = false,
            isFavorite = false,
            Post.Donut(false, 102, placeHolder = "Some String", false, Post.Donut.EditMode.all),
            42))

        val serviceCheck0 = Post(1,
            25,
            59,
            12,
            1647797692,
            "New Netology Post",
            37,
            84,
            true,
            Post.Comments(2, true, 4, canClose = false, canOpen = false),
            Post.Copyright(83, "https://--", "Some Name", "Some Type"),
            Post.Likes(95, userLikes = false, canLike = true, canPublish = false),
            Post.Reposts(47, true),
            Post.Views(2),
            Post.PostType.post,
            25,
            canPin = true,
            canDelete = false,
            canEdit = false,
            isPinned = true,
            markedAsAds = false,
            isFavorite = false,
            Post.Donut(false, 102, placeHolder = "Some String", false, Post.Donut.EditMode.all),
            42)

        assertEquals(serviceCheck0.id, serviceEnter0.posts[0].id)

        val serviceEnterId8 = serviceEnter0
        serviceEnterId8.add(Post(2,
            31,
            43,
            14,
            1647797883,
            "Second Netology Post",
            38,
            137,
            false,
            Post.Comments(5, false, 4, canClose = false, canOpen = true),
            Post.Copyright(83, "https://--", "Some Name", "Some Type"),
            Post.Likes(95, userLikes = false, canLike = true, canPublish = true),
            Post.Reposts(47, false),
            Post.Views(15),
            Post.PostType.suggest,
            47,
            canPin = false,
            canDelete = false,
            canEdit = true,
            isPinned = false,
            markedAsAds = false,
            isFavorite = true,
            Post.Donut(true, 102, placeHolder = "Some Second String", true, Post.Donut.EditMode.all),
            70))

        assertEquals(2, serviceEnterId8.posts[1].id)
    }

    @Test
    fun updateExisting() {
        // создаём целевой сервис
        val service = WallService()

        // заполняем несколькими постами
        service.add(Post(0,
            25,
            59,
            12,
            1647797692,
            "New Netology Post",
            37,
            84,
            true,
            Post.Comments(2, true, 4, canClose = false, canOpen = false),
            Post.Copyright(83, "https://--", "Some Name", "Some Type"),
            Post.Likes(95, userLikes = false, canLike = true, canPublish = false),
            Post.Reposts(47, true),
            Post.Views(2),
            Post.PostType.post,
            25,
            canPin = true,
            canDelete = false,
            canEdit = false,
            isPinned = true,
            markedAsAds = false,
            isFavorite = false,
            Post.Donut(false, 102, placeHolder = "Some String", false, Post.Donut.EditMode.all),
            42))

        service.add(Post(2,
            31,
            43,
            14,
            1647797883,
            "Second Netology Post",
            38,
            137,
            false,
            Post.Comments(5, false, 4, canClose = false, canOpen = true),
            Post.Copyright(83, "https://--", "Some Name", "Some Type"),
            Post.Likes(95, userLikes = false, canLike = true, canPublish = true),
            Post.Reposts(47, false),
            Post.Views(15),
            Post.PostType.suggest,
            47,
            canPin = false,
            canDelete = false,
            canEdit = true,
            isPinned = false,
            markedAsAds = false,
            isFavorite = true,
            Post.Donut(true, 102, placeHolder = "Some Second String", true, Post.Donut.EditMode.all),
            70))

        service.add(Post(id = 3,
            ownerId = 63,
            fromId = 13,
            createdBy = 75,
            date = 19,
            text = "Updated Netology Post",
            replyOwnerId = 135,
            replyPostId = 66,
            friendsOnly = true,
            comments = Post.Comments(9, true, 5, canClose = true, canOpen = true),
            copyright = Post.Copyright(85, "https://site-updated", "Some Updated Name", "Some Updated Type"),
            likes = Post.Likes(96, userLikes = false, canLike = true, canPublish = false),
            reposts = Post.Reposts(8, false),
            views = Post.Views(7),
            postType = Post.PostType.postpone,
            signerId = 61,
            canPin = true,
            canDelete = false,
            canEdit = true,
            isPinned = false,
            markedAsAds = true,
            isFavorite = true,
            donut = Post.Donut(true, 8, "Some Old String", false, Post.Donut.EditMode.all),
            postponedId = 40))

        // создаём информацию об обновлении для true
        val update = Post(id = 3,
            ownerId = 111,
            fromId = 56,
            createdBy = 15,
            date = 13,
            text = "Updated Netology Post",
            replyOwnerId = 103,
            replyPostId = 87,
            friendsOnly = false,
            comments = Post.Comments(9, false, 5, canClose = true, canOpen = false),
            copyright = Post.Copyright(85, "https://site-updated", "Some Updated Name", "Some Updated Type"),
            likes = Post.Likes(96, userLikes = true, canLike = true, canPublish = true),
            reposts = Post.Reposts(48, false),
            views = Post.Views(10),
            postType = Post.PostType.reply,
            signerId = 61,
            canPin = false,
            canDelete = false,
            canEdit = true,
            isPinned = false,
            markedAsAds = true,
            isFavorite = false,
            donut = Post.Donut(false, 118, "Some Updated String", true, Post.Donut.EditMode.duration),
            postponedId = 38)

        val result = service.update(update)
        assertTrue(result)

        val updateFalse = Post(id = 6,
            ownerId = 111,
            fromId = 56,
            createdBy = 15,
            date = 13,
            text = "Updated Netology Post",
            replyOwnerId = 103,
            replyPostId = 87,
            friendsOnly = false,
            comments = Post.Comments(9, false, 5, canClose = true, canOpen = false),
            copyright = Post.Copyright(85, "https://site-updated", "Some Updated Name", "Some Updated Type"),
            likes = Post.Likes(96, userLikes = true, canLike = true, canPublish = true),
            reposts = Post.Reposts(48, false),
            views = Post.Views(10),
            postType = Post.PostType.reply,
            signerId = 61,
            canPin = false,
            canDelete = false,
            canEdit = true,
            isPinned = false,
            markedAsAds = true,
            isFavorite = false,
            donut = Post.Donut(false, 118, "Some Updated String", true, Post.Donut.EditMode.duration),
            postponedId = 38)

        val resultFalse = service.update(updateFalse)
        assertFalse(resultFalse)
    }
}