import org.junit.Test
import org.junit.Assert.*

class WallServiceTest {

    @Test
    fun add() {
        val serviceEnter0 = WallService()
        serviceEnter0.add(Post(0,
            25,
            59,
            12,
            1647797692,
            "New Netology Post",
            37,
            84,
            true,
            Comments(2, true, 4, canClose = false, canOpen = false),
            Copyright(83, "https://--", "Some Name", "Some Type"),
            Likes(95, userLikes = false, canLike = true, canPublish = false),
            Reposts(47, true),
            Views(2),
            PostType.Post,
            PostSource(PostSource.Type.Vk,"",""," https://vk.com/"),
            attachments = arrayOf(
                VideoAttachment("video", Video(25, 12, 2, 5,"My walk")),
                AudioAttachment("audio", Audio( 3, 17, 3, 309, "Florida")),
                PhotoAttachment("photo", Photo( 5, 10, 3, 38, "MyTripToSouth")),
                DocAttachment("doc", Doc(8, 402, 15, ".doc", 153)),
                ContactAttachment("contact", Contact( 11, 42, 10, "Home","+7-918-356-37-82")),
            ),
            Geo("","",Geo.Place(1,"",253511,101537,1647797883,"",5,1647797883,2,159,25,"")),
            25,
            copyHistory = (arrayOf(Reposts(49, false), Reposts(50, true))),
            //copyHistory = null,
            canPin = true,
            canDelete = false,
            canEdit = false,
            isPinned = true,
            markedAsAds = false,
            isFavorite = false,
            Donut(false, 102, placeHolder = "Some String", false, Donut.EditMode.all),
            42))

        val serviceCheck0 = Post(1,
            25,
            59,
            12,
            1647797692,
            "New Netology Post",
            37,
            84,
            true,
            Comments(2, true, 4, canClose = false, canOpen = false),
            Copyright(83, "https://--", "Some Name", "Some Type"),
            Likes(95, userLikes = false, canLike = true, canPublish = false),
            Reposts(47, true),
            Views(2),
            PostType.Post,
            PostSource(PostSource.Type.Vk,"",""," https://vk.com/"),
            attachments = arrayOf(
                VideoAttachment("video", Video(25, 12, 2, 5,"My walk")),
                AudioAttachment("audio", Audio( 3, 17, 3, 309, "Florida")),
                PhotoAttachment("photo", Photo( 5, 10, 3, 38, "MyTripToSouth")),
                DocAttachment("doc", Doc(8, 402, 15, ".doc", 153)),
                ContactAttachment("contact", Contact( 11, 42, 10, "Home","+7-918-356-37-82")),
            ),
            Geo("","",Geo.Place(1,"",253511,101537,1647797883,"",5,1647797883,2,159,25,"")),
            25,
            //copyHistory = (arrayOf(Post.Reposts(49, false), Post.Reposts(50, true))),
            copyHistory = null,
            canPin = true,
            canDelete = false,
            canEdit = false,
            isPinned = true,
            markedAsAds = false,
            isFavorite = false,
            Donut(false, 102, placeHolder = "Some String", false, Donut.EditMode.all),
            42)

        assertEquals(serviceCheck0.id, serviceEnter0.posts[0].id)

        val serviceEnterId8 = serviceEnter0
        serviceEnterId8.add(Post(2,
            31,
            43,
            14,
            1647797883,
            "Second Netology Post",
            38,
            137,
            false,
            Comments(5, false, 4, canClose = false, canOpen = true),
            Copyright(83, "https://--", "Some Name", "Some Type"),
            Likes(95, userLikes = false, canLike = true, canPublish = true),
            Reposts(47, false),
            Views(15),
            PostType.Suggest,
            PostSource(PostSource.Type.Rss,null,null," https://vk.com/"),
            attachments = arrayOf(
                VideoAttachment("video", Video(25, 12, 2, 5,"My walk")),
                AudioAttachment("audio", Audio( 3, 17, 3, 309, "Florida")),
                PhotoAttachment("photo", Photo( 5, 10, 3, 38, "MyTripToSouth")),
                DocAttachment("doc", Doc(8, 402, 15, ".doc", 153)),
                ContactAttachment("contact", Contact( 11, 42, 10, "Home","+7-918-356-37-82")),
            ),
            Geo("","",Geo.Place(2,"",253511,101580,1647797905,"",5,1647797905,1,183,29,"")),
            47,
            //copyHistory = (arrayOf(Post.Reposts(49, false), Post.Reposts(51, false))),
            copyHistory = null,
            canPin = false,
            canDelete = false,
            canEdit = true,
            isPinned = false,
            markedAsAds = false,
            isFavorite = true,
            Donut(true, 102, placeHolder = "Some Second String", true, Donut.EditMode.all),
            70))

        assertEquals(2, serviceEnterId8.posts[1].id)
    }

    @Test
    fun updateExisting() {
        val service = WallService()

        service.add(Post(0,
            25,
            59,
            12,
            1647797692,
            "New Netology Post",
            37,
            84,
            true,
            Comments(2, true, 4, canClose = false, canOpen = false),
            Copyright(83, "https://--", "Some Name", "Some Type"),
            Likes(95, userLikes = false, canLike = true, canPublish = false),
            Reposts(47, true),
            Views(2),
            PostType.Post,
            PostSource(null,null,null," https://vk.com/"),
            attachments = arrayOf(
                VideoAttachment("video", Video(25, 12, 2, 5,"My walk")),
                AudioAttachment("audio", Audio( 3, 17, 3, 309, "Florida")),
                PhotoAttachment("photo", Photo( 5, 10, 3, 38, "MyTripToSouth")),
                DocAttachment("doc", Doc(8, 402, 15, ".doc", 153)),
                ContactAttachment("contact", Contact( 11, 42, 10, "Home","+7-918-356-37-82")),
            ),
            Geo("MyTypePlace","N:253511,W:101537",null),
            25,
            //copyHistory = (arrayOf(Post.Reposts(49, false), Post.Reposts(50, true))),
            copyHistory = null,
            canPin = true,
            canDelete = false,
            canEdit = false,
            isPinned = true,
            markedAsAds = false,
            isFavorite = false,
            Donut(false, 102, placeHolder = "Some String", false, Donut.EditMode.all),
            42))

        service.add(Post(2,
            31,
            43,
            14,
            1647797883,
            "Second Netology Post",
            38,
            137,
            false,
            Comments(5, false, 4, canClose = false, canOpen = true),
            Copyright(83, "https://--", "Some Name", "Some Type"),
            Likes(95, userLikes = false, canLike = true, canPublish = true),
            Reposts(47, false),
            Views(15),
            PostType.Suggest,
            PostSource(PostSource.Type.Api,"",""," https://vk.com/"),
            attachments = arrayOf(
                VideoAttachment("video", Video(25, 12, 2, 5,"My walk")),
                AudioAttachment("audio", Audio( 3, 17, 3, 309, "Florida")),
                PhotoAttachment("photo", Photo( 5, 10, 3, 38, "MyTripToSouth")),
                DocAttachment("doc", Doc(8, 402, 15, ".doc", 153)),
                ContactAttachment("contact", Contact( 11, 42, 10, "Home","+7-918-356-37-82")),
            ),
            Geo("","",Geo.Place(2,"",253511,101580,1647797905,"",5,1647797905,1,183,29,"")),
            47,
            copyHistory = (arrayOf(Reposts(49, false), Reposts(51, false))),
            //copyHistory = null,
            canPin = false,
            canDelete = false,
            canEdit = true,
            isPinned = false,
            markedAsAds = false,
            isFavorite = true,
            Donut(true, 102, placeHolder = "Some Second String", true, Donut.EditMode.all),
            70))

        service.add(Post(id = 3,
            ownerId = 63,
            fromId = 13,
            createdBy = 75,
            date = 19,
            text = "Updated Netology Post",
            replyOwnerId = 135,
            replyPostId = 66,
            friendsOnly = true,
            comments = Comments(9, true, 5, canClose = true, canOpen = true),
            copyright = Copyright(85, "https://site-updated", "Some Updated Name", "Some Updated Type"),
            likes = Likes(96, userLikes = false, canLike = true, canPublish = false),
            reposts = Reposts(8, false),
            views = Views(7),
            postType = PostType.Postpone,
            postSource = PostSource(PostSource.Type.Rss,"",""," https://vk.com/"),
            attachments = arrayOf(
                VideoAttachment("video", Video(25, 12, 2, 5,"My walk")),
                AudioAttachment("audio", Audio( 3, 17, 3, 309, "Florida")),
                PhotoAttachment("photo", Photo( 5, 10, 3, 38, "MyTripToSouth")),
                DocAttachment("doc", Doc(8, 402, 15, ".doc", 153)),
                ContactAttachment("contact", Contact( 11, 42, 10, "Home","+7-918-356-37-82")),
            ),
            geo = Geo("","",Geo.Place(2,"",253511,101580,1647797905,"",5,1647797905,1,183,29,"")),
            signerId = 61,
            copyHistory = (arrayOf(Reposts(49, false), Reposts(51, false))),
            //copyHistory = null,
            canPin = true,
            canDelete = false,
            canEdit = true,
            isPinned = false,
            markedAsAds = true,
            isFavorite = true,
            donut = Donut(true, 8, "Some Old String", false, Donut.EditMode.all),
            postponedId = 40))

        val update = Post(id = 3,
            ownerId = 111,
            fromId = 56,
            createdBy = 15,
            date = 13,
            text = "Updated Netology Post",
            replyOwnerId = 103,
            replyPostId = 87,
            friendsOnly = false,
            comments = Comments(9, false, 5, canClose = true, canOpen = false),
            copyright = Copyright(85, "https://site-updated", "Some Updated Name", "Some Updated Type"),
            likes = Likes(96, userLikes = true, canLike = true, canPublish = true),
            reposts = Reposts(48, false),
            views = Views(10),
            postType = PostType.Reply,
            postSource = PostSource(PostSource.Type.Sms,"",""," https://vk.com/"),
            attachments = arrayOf(
                VideoAttachment("video", Video(25, 12, 2, 5,"My walk")),
                AudioAttachment("audio", Audio( 3, 17, 3, 309, "Florida")),
                PhotoAttachment("photo", Photo( 5, 10, 3, 38, "MyTripToSouth")),
                DocAttachment("doc", Doc(8, 402, 15, ".doc", 153)),
                ContactAttachment("contact", Contact( 11, 42, 10, "Home","+7-918-356-37-82")),
            ),
            geo = Geo("","",Geo.Place(2,"",253511,101580,1647797905,"",5,1647797905,1,183,29,"")),
            signerId = 61,
            //copyHistory = (arrayOf(Post.Reposts(49, false), Post.Reposts(51, false))),
            copyHistory = null,
            canPin = false,
            canDelete = false,
            canEdit = true,
            isPinned = false,
            markedAsAds = true,
            isFavorite = false,
            donut = Donut(false, 118, "Some Updated String", true, Donut.EditMode.duration),
            postponedId = 38)

        val result = service.update(update)
        assertTrue(result)

        val updateFalse = Post(id = 6,
            ownerId = 111,
            fromId = 56,
            createdBy = 15,
            date = 13,
            text = "Updated Netology Post",
            replyOwnerId = 103,
            replyPostId = 87,
            friendsOnly = false,
            comments = Comments(9, false, 5, canClose = true, canOpen = false),
            copyright = Copyright(85, "https://site-updated", "Some Updated Name", "Some Updated Type"),
            likes = Likes(96, userLikes = true, canLike = true, canPublish = true),
            reposts = Reposts(48, false),
            views = Views(10),
            postType = PostType.Reply,
            postSource = PostSource(PostSource.Type.Widget,"",""," https://vk.com/"),
            attachments = arrayOf(
                VideoAttachment("video", Video(25, 12, 2, 5,"My walk")),
                AudioAttachment("audio", Audio( 3, 17, 3, 309, "Florida")),
                PhotoAttachment("photo", Photo( 5, 10, 3, 38, "MyTripToSouth")),
                DocAttachment("doc", Doc(8, 402, 15, ".doc", 153)),
                ContactAttachment("contact", Contact( 11, 42, 10, "Home","+7-918-356-37-82")),
            ),
            geo = Geo("","",Geo.Place(2,"",253511,101580,1647797905,"",5,1647797905,1,183,29,"")),
            signerId = 61,
            //copyHistory = (arrayOf(Post.Reposts(49, false), Post.Reposts(51, false))),
            copyHistory = null,
            canPin = false,
            canDelete = false,
            canEdit = true,
            isPinned = false,
            markedAsAds = true,
            isFavorite = false,
            donut = Donut(false, 118, "Some Updated String", true, Donut.EditMode.duration),
            postponedId = 38)

        val resultFalse = service.update(updateFalse)
        assertFalse(resultFalse)
    }
}